# Copyright (C) <2011>  <Scott Smith> <smitherz82@gmail.com>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

our %module_home_header = (
	module_name => 'home',
	menu_title => 'Home',
	frame => &home_frame,
	rank => 1
);

sub home
{
	return %module_home_header;
}

sub home_frame
{
	my $vbox = Gtk2::VBox->new(FALSE,5);
	my $lbl=Gtk2::Label->new('Home');

	$vbox->pack_end($lbl,TRUE,TRUE,0);
	$vbox->show_all;
	return $vbox;
}

1;
